const head = () => {
  return (
    <>
      <title> search | AddaKhana</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta name="description" content="Generated by create next app" />
    </>
  );
};

export default head;
