import Navbar from "./components/Navbar";
import "./globals.css";

export const metadata = {
  title: "AddaKhana",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/favicon.png" />
      </head>
      <body>
        <main className="bg-gray-200 min-h-screen w-screen">
          <div className="max-w-screen-2xl m-auto bg-white">
            <Navbar />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
