import Navbar from "./components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "AddaKhana",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <head>
        <link rel="shortcut icon" href="/favicon.png" />
      </head>
      <body>
        <main className="bg-gray-200 min-h-screen w-screen">
          <div className="bg-white">
            <Navbar />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
